import { Box, Flex } from '@chakra-ui/react/dist';
import Head from 'next/head'
import Image from 'next/image'
// import { Inter } from '@next/font/google'
// import styles from '../styles/Home.module.css'
import Navbar from '../Components/Navbar'
import Profile from '../Components/Profile';

// const inter = Inter({ subsets: ['latin'] })

export default function Home({ rdata }) {
console.log(rdata);
  return (
    <>
      <Head>
        <title>Rohan Github App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <div >
        {/*className={styles.main} className={styles.description} */}
          <Navbar />
          <Flex>
            <Box>
              <Profile 
                name={rdata.name} 
                login={rdata.login}
                bio={rdata.bio}
                />
            </Box>
            <Box></Box>
          </Flex>
        </div>
      </main>
    </>
  )
}


export async function getStaticProps() {
  let res = await fetch(`https://api.github.com/users/rohan28107`);
  let data = await res.json();
  return {
    props: {
      rdata: data
    }
  }
}